### ISSUE TITLE
We need Class and Section information 

### ISSUE THREAD

**Issue by meghaklp** [klpdotorg/tada-frontend#103]
Hard to distinguish so many class 2(s)

![image](https://cloud.githubusercontent.com/assets/465382/20657027/b049c6f8-b558-11e6-8d44-2bc9c7eb7210.png)

**Comment by subhaklp** [comment]
@aksanoble will fix it before Dec 30..

**Comment by meghaklp** [comment]
Not fixed - moving to Beta 1

**Comment by meghaklp** [comment]
Works on staging for now.
