### ISSUE TITLE
Decide on doing bulk edit/delete of assessments

### ISSUE THREAD

**Issue by subhaklp** [klpdotorg/tada-frontend#107]
I chatted with Haris about this on Slack. But wanted to get everyone on the same page about this.

So the UI mockups for assessments call for bulk activation/deactivation of assessments. But the REST endpoints are all unique for each assessment. i.e. there's an assessment id in the URL which precludes any bulk operation.There are two options to achieve this:

1. Frontend code will just loop through all selected assessments and issue deletes one by one. This is more work on the frontend part but it is do-able.
2. Or since we've already done bulk edit of students (and broken REST standards..:)), we can do it again for the assessments endpoint. This will be easier for the frontend but I don't know about the server side of things.

Not particularly supporting 1 or 2. Just want to hear from you guys. @aksanoble @harisibrahimkv

**Comment by harisibrahimkv** [comment]
Do we support bulk `edit` on students? Can you give me an example of the endpoint used and the JSON being passed from the frontend for this?

**Comment by subhaklp** [comment]
We decided to do this as an enhancement. Bug already open with Haris on the server repo. Closing this as redundant.
