### ISSUE TITLE
UX for activating/deactivating programs

### ISSUE THREAD

**Issue by subhaklp** [klpdotorg/tada-frontend#116]
- [ ] Programs are active annually and they get deactivated at the end of the year. The TADA programs list only shows active programs. We need to figure out how to deactivate programs from the UI.

- [ ] Create program dialog shows an "Active/Inactive" option right now. If all programs are active by default, we shouldn't show this? Or maybe we create a program in advance and activate it later? What's the use case?

- [ ] Based on above, we need to figure out whether the edit dialog shows a deactivate button or maybe in the program details box or somewhere.

@meghaklp , please comment when you get some time to ponder.

**Comment by meghaklp** [comment]
1) I've indicated on the mock up, that we add a button alongside Edit, delete I can style the buttons later https://raw.githubusercontent.com/klpdotorg/tada_ui/master/workflow_mockups/Admin_ManagePrograms.jpg

2) the workflow mock up does not have status. - https://raw.githubusercontent.com/klpdotorg/tada_ui/master/workflow_mockups/Admin_AddProgram.jpg
by default a new program created should be active

3) Edit need not show status, as we are controlling status alongside the edit button. 

Activating a deactivated program/assessment is an enhancement we can look at later.
