### ISSUE TITLE
Create School Modal is too small, and buggy

### ISSUE THREAD

**Issue by meghaklp** [klpdotorg/tada-frontend#132]
![image](https://cloud.githubusercontent.com/assets/465382/23018773/4de2f308-f465-11e6-9f1f-b523eff983e7.png)

**Comment by meghaklp** [comment]
We still have only 2 fields on the modal. And on the create modal Medium of Instruction is called "Languages" and on the Edit screen "Medium". Let's call it medium in both places.

**Comment by vibhutipratapsingh** [comment]
Added other Fields same as modify schools.
Added form validation
