### ISSUE TITLE
Create Class is not as per spec

### ISSUE THREAD

**Issue by meghaklp** [klpdotorg/tada-frontend#133]
CLass has 3 attributes - Name, Section, Type. We should be able to input this during creation.
Here's the modify screen
https://github.com/klpdotorg/tada/wiki/Work-Flow-Mock-ups#workflow-modify-class

**Comment by meghaklp** [comment]
Type should have centre/class

**Comment by subhaklp** [comment]
One more for @vibhutipratapsingh to look at.

**Comment by vibhutipratapsingh** [comment]
Added options class and center in group_type
