### ISSUE TITLE
Delete School does not work

### ISSUE THREAD

**Issue by meghaklp** [klpdotorg/tada-frontend#136]
And the modal is blocking me- neither clicking yes nor no makes the modal go away:

![image](https://cloud.githubusercontent.com/assets/465382/23019318/b9aaf4da-f467-11e6-8c0a-4dc99be896d3.png)

**Comment by subhaklp** [comment]
@vibhutipratapsingh another one for you to look at..

**Comment by vibhutipratapsingh** [comment]
Delete school working now.
