### ISSUE TITLE
Create Program - Issues

### ISSUE THREAD

**Issue by meghaklp** [klpdotorg/tada-frontend#137]
1. Can we default the Start date to today's date and end date to a year from now
2. Default status during creation should be active. I wonder if we need this, because even if I create an inactive program it shows in the drop down. But if I deactivate/ delete a program it disappears from the drop down.
3. And I am wondering if in the Primary school tab we should see only primary school programs and preschool tab have only preschool programs.
4. On successful creation of the program, can the selection and screen behind the modal be set to the newly created program?

![image](https://cloud.githubusercontent.com/assets/465382/23019448/7074e590-f468-11e6-9d93-cc24480981ee.png)

**Comment by brijeshpoojary** [comment]
+1 on 2) I dont think we would need that active thing to be asked.

**Comment by subhaklp** [comment]
@meghaklp re #3, do you think it'd be that obvious for someone to see that the tabs on the left and the content on the right is connected in this case?

@subhaklp We could add an additional drop down. But the tabs are meant to set global context for the right frame. We can hide/ not show the nav tree.

**Comment by subhaklp** [comment]
Aye to #1,2,4. Working on it.

**Comment by subhaklp** [comment]
This is done. I'll push to TADA staging tomorrow and then can be tested.

**Comment by subhaklp** [comment]
#3 has its own separate bug opened by Brijesh. So we can close this if 1,2,4 are fixed.

**Comment by meghaklp** [comment]
1,2,4 reviewed
