### ISSUE TITLE
Edit Program - Not working

### ISSUE THREAD

**Issue by meghaklp** [klpdotorg/tada-frontend#138]
Can Edit and save only if I change program name, I think. If I try to modify the description/start date/end date of the program alone, I get this error:

![image](https://cloud.githubusercontent.com/assets/465382/23019547/e9b1b80c-f468-11e6-8a77-3a5c5a487c92.png)

**Comment by subhaklp** [comment]
Fixed this. Was a bug with the formsy-react component we use for validation. Unless a default value was modified, the field always returned null.

**Comment by meghaklp** [comment]
Works
