### ISSUE TITLE
drop down list for class and programmes

### ISSUE THREAD

**Issue by brijeshpoojary** [klpdotorg/tada-frontend#150]
These dropdowns show preschool classes and programmes for primary school tab.

Here : http://tada-staging.klp.org.in:3000/district/414/block/462/cluster/725/institution/1933/studentgroups/2389804

**Comment by brijeshpoojary** [comment]
![screenshot from 2017-02-28 10 23 39](https://cloud.githubusercontent.com/assets/2518207/23392215/21e9cef4-fda0-11e6-9f66-be4f684f750d.png)

**Comment by subhaklp** [comment]
Have asked @harisibrahimkv for an update on whether the server supports filtering by primary/preschool.

**Comment by subhaklp** [comment]
I've fixed this now. Pending review by Brijesh.
