### ISSUE TITLE
Clicking on View Student takes me back to Cluster page

### ISSUE THREAD

**Issue by subhaklp** [klpdotorg/tada-frontend#175]
If I click on "View Students" under a class, it takes me back to the cluster page. Either we should see a message saying there are no students or it should show students. NOt sure why its behaving this way. Needs to be fixed. I tested this portion of the nav tree:
bangalore u north>north-4>abbigere>GULPS MEDIAGRAHARA>2C and then click on View Students.

**Comment by vibhutipratapsingh** [comment]
Fixed View Student bug. Added message when no student is present.
