### ISSUE TITLE
Fix alignment of permissions icon and the border below it..

### ISSUE THREAD

**Issue by subhaklp** [klpdotorg/tada-frontend#185]
Megha,

To recreate this issue, login as tadadeo/tadadeo1. Navigate down to Dharwad->Hubli ->aralikatti. Select any institution. The alignment of the "Insufficient Permissions" icon and the border below are messed up. A long time ago, I created a style called "heading-border-left" to add the line below. But I think it is messed up majorly. Please help in fixing this! This is in the InstitutionDetailsScreen.jsx.

**Comment by meghaklp** [comment]
Fixed these across all pages too.
