### ISSUE TITLE
Extend bootstrap modal styles to suit KLP

### ISSUE THREAD

**Issue by subhaklp** [klpdotorg/tada-frontend#195]
I am using bootstrap's modal-dialog, modal-content, modal-header, modal-body styles for all our modals because it was most convenient at that time.  modal-dialog adds a 30px padding/margin on top which we don't want. Also, we want the modal-header to stay fixed while adding a scrollbar to the modal-body. Need to be able to extend bootstrap's classes and modify them a bit to suit our needs. Look under the components/Modals directory for examples.

**Comment by meghaklp** [comment]
@subhaklp I've fixed the modal to have a max-height and 10 px padding all around so all modals render in default style. So the extra padding around smaller modals is not there anymore.

I've looked around to see if we can use the react -bootstrap modal in such a fashion where the header is fixed and the body is scroll-able. I couldn't find a solution. If we need to make it work, we'll probably have to modify the package level css. The other alternative is building a custom modal to be able to fix the header and scroll on fields, etc. Or using a different package. 

I'll leave this bug to Ansal/ Pankaj
