### ISSUE TITLE
Modifying District

### ISSUE THREAD

**Issue by meghaklp** [klpdotorg/tada-frontend#202]
When I try to modify a District, a new District is created, See modification on the right and the tree on the left with the new district

![image](https://cloud.githubusercontent.com/assets/465382/25468802/da6fa616-2b35-11e7-9fde-69708281ef8e.png)

And for some reason this new district has these blocks under it already and I can't delete it either:

![image](https://cloud.githubusercontent.com/assets/465382/25468824/0ecdee40-2b36-11e7-921e-1e992450f3f6.png)

**Comment by subhaklp** [comment]
@meghaklp I am not seeing this behavior at all. I modified AB_NewDistrict on tada-staging and made it AB_NewDistrict_Test, it is just modifying existing district. @vibhutipratapsingh can you try and recreate this problem?

**Comment by meghaklp** [comment]
@subhaklp @vibhutipratapsingh I think it's to do with having 2 nodes open... but I'm not sure. I mentioned on another bug, that maybe at a time we should have only one node on the tree expanded. So, every time i open one, all other open nodes could be closed.

**Comment by meghaklp** [comment]
@subhaklp @vibhutipratapsingh 
Also these maybe the exact steps:
1) Create a new district
2) The new district gets added to the nav tree and the modify splash comes to the right frame, modify the name of the newly created district
3) Another new district is getting added on the nav tree with the modified name.

**Comment by subhaklp** [comment]
Yes, I see it now.

**Comment by subhaklp** [comment]
Seeing this bug on tada-staging but its not happening with latest code on my local environment. Doesn't manifest on tadadev either. Wondering if this is a code burp of some kind on tada staging..will push new code to tada-staging and then test again.

**Comment by subhaklp** [comment]
@meghaklp I pushed new code on tada-staging just now and I am not seeing this problem any more. Can you please spend 5 minutes and see if you still see this?

**Comment by meghaklp** [comment]
Seems fine now. Closing @subhaklp @vibhutipratapsingh
