### ISSUE TITLE
Create Class/ Center - Unable to create centers/Map to Centers

### ISSUE THREAD

**Issue by meghaklp** [klpdotorg/tada-frontend#204]
1) Something is buggy about this modal, if I type text in the name field I can't proceed further
2) Section is not mandatory, because we can't have a section for center
3) On creation of the class we should be at the modify class point on the nav tree, currently goes back to modify school/

![image](https://cloud.githubusercontent.com/assets/465382/25469980/63d08400-2b3d-11e7-88e5-93e76214c087.png)

**Comment by vibhutipratapsingh** [comment]
Actually validation for class  was it should be numeric. If have changed it to alphanumeric. Now It should work.

**Comment by subhaklp** [comment]
Ansal, just verify this before marking it for review.
