### ISSUE TITLE
Edit Student - Issues

### ISSUE THREAD

**Issue by meghaklp** [klpdotorg/tada-frontend#205]
Gender, Language should be drop downs

**Comment by meghaklp** [comment]
![image](https://cloud.githubusercontent.com/assets/465382/25470323/4f5200ce-2b3f-11e7-8642-11fa9c0dba13.png)

**Comment by meghaklp** [comment]
Let's call Language - "Mother Tongue" please.

And on the School creation/ modification it should be "Medium of Instruction"

**Comment by meghaklp** [comment]
On the Modify modal - Buttons should be consistent with the rest. Currently says YES/NO - Should be Save/Discard

![image](https://cloud.githubusercontent.com/assets/465382/25470380/9d781f0e-2b3f-11e7-90e7-a9feeb642983.png)

**Comment by vibhutipratapsingh** [comment]
Please tell me the list of languages that should be in the dropdown of mother tongue.
I have added english and hindi for now.

**Comment by meghaklp** [comment]
@vibhutipratapsingh @aksanoble - this list of languages should come from the DB

**Comment by meghaklp** [comment]
Medium of Instruction and Mother tongue have the same list of languages
