### ISSUE TITLE
Deactivate Assessment disabled

### ISSUE THREAD

**Issue by meghaklp** [klpdotorg/tada-frontend#207]
@subhaklp Why?

**Comment by subhaklp** [comment]
@meghaklp because you have to select assessments to enable that button?

**Comment by meghaklp** [comment]
So this is when I've selected the assessment and hover over deactivate

![image](https://cloud.githubusercontent.com/assets/465382/25553379/7bc37412-2ccf-11e7-8b58-b444b50ce3e7.png)

This is when I click deactivate - Selection gets unchecked and the button gets disabled:

![image](https://cloud.githubusercontent.com/assets/465382/25553398/aa8d2518-2ccf-11e7-83e7-612065670ceb.png)

**Comment by subhaklp** [comment]
I fixed a bug on the frontend for this. But I also need to fetch active assessments only from the server. I need a server filter for this. Have pinged @harisibrahimkv about it. Will close it out when I hear back.

**Comment by harisibrahimkv** [comment]
It's already there. `"http://localhost:8000/api/v1/assessments/?active=0"` works. 0, 1 and 2 are the values.

**Comment by subhaklp** [comment]
Fixed.
