### ISSUE TITLE
New User

### ISSUE THREAD

**Issue by meghaklp** [klpdotorg/tada-frontend#208]
Can't seem to create a new user. Some validation is failing

![image](https://cloud.githubusercontent.com/assets/465382/25472313/73d38fc2-2b48-11e7-9a82-a9f4bf683299.png)

**Comment by vibhutipratapsingh** [comment]
The validation on password is minimum length should be  8. I think This may be the reason that it is not saving user.

**Comment by subhaklp** [comment]
@vibhutipratapsingh did you fix this? Else, I will.

**Comment by vibhutipratapsingh** [comment]
I have added the message that password should be atleast 8 chars long.

Vibhuti Pratap Singh
The LNM Institute of Information Technology, Jaipur, India
B.Tech (Computer Science and Engineering)
LinkedIn : LinkedIn <https://www.linkedin.com/in/vibhutipratapsingh>
Website : personalWebsite <http://vibhuti-singh.appspot.com/>
Phone Number:- (+91)9505389250
Gate Score:-658

**Comment by vibhutipratapsingh** [comment]
It is giving error Object.values is not a function(). @subhaklp It will be good if you take a look at it. I have pushed the changes in develop branch.

**Comment by vibhutipratapsingh** [comment]
@subhaklp Actually It is user is created in my firefox browser. But not it chrome. I think issue is resolved. You please check it.

**Comment by subhaklp** [comment]
ok, i will take a look..thanks.

**Comment by subhaklp** [comment]
This is fixed. I also implemented creating a firstname, lastname by PATCHing the users endpoint. Once @harisibrahimkv fixes the register endpoint, we'll have to remove this extra call.

**Comment by vibhutipratapsingh** [comment]
Hello there,

I just signed the petition "Government of India: 14th February be declared
as Veergathi Divas" and wanted to see if you could help by adding your name.

Our goal is to reach 7,500 signatures and we need more support. You can
read more and sign the petition here:

http://chng.it/F5BMGQ8kCg

Thanks!
Vibhuti Pratap
