### ISSUE TITLE
Deactivating Users

### ISSUE THREAD

**Issue by meghaklp** [klpdotorg/tada-frontend#209]
@subhaklp - when I deactivate a user they still show on the User list. Is that expected? There's no indication that deactivation happened. So, should we show status on the table. Otherwise it's hard to distinguish.

Then maybe we should have activate user also.

**Comment by subhaklp** [comment]
@meghaklp this is a bug. I'll remove the deactivated users from the list..am fetching only active users from the server anyway.

**Comment by subhaklp** [comment]
This is fixed now.
