### ISSUE TITLE
Permissions page - need scrolling table, fixed headers

### ISSUE THREAD

**Issue by subhaklp** [klpdotorg/tada-frontend#217]
In the "Manage Permissions" page (reached via admin toolbar), there are three tables - one each for boundary, users, assessments. All these tables need to have fixed headers and scrolling bodies. app/components/Permissions.jsx is the file for this component. custom.css under assets is where any custom styling can go in. Assigning this to Megha for now.

**Comment by meghaklp** [comment]
@subhaklp - Is this bug still valid? I see you have scrolling tables and fixed headers.
