### ISSUE TITLE
Admin Role - Boundary CRUD

### ISSUE THREAD

**Issue by meghaklp** [klpdotorg/tada-frontend#29]
District (school/preschool) CRUD
- [x] View District
- [x] [Create a District](https://github.com/klpdotorg/tada_ui/blob/master/workflow_mockups/Admin_AddDistrict.jpg)
- [x] Modify District
- [x] Delete District

Block / Project CRUD
- [x] View Block / Project
- [ ] Create a Block / Project
- [x] [Modify Block / Project](https://github.com/klpdotorg/tada_ui/blob/master/workflow_mockups/Admin_ModifyBlock.jpg)
- [x] Delete Block / Project

Cluster / Circle CRUD
- [x] View Cluster/ Circle
- [ ] Create a Cluster / Circle
- [x] [Modify Cluster /Circle](https://github.com/klpdotorg/tada_ui/blob/master/workflow_mockups/Admin_ModifyCluster.jpg)
- [x] Delete Cluster/ Circle

DEO Role can't modify[ Block](https://github.com/klpdotorg/tada_ui/blob/master/workflow_mockups/Admin_ModifyBlock.jpg) or [Cluster](https://github.com/klpdotorg/tada_ui/blob/master/workflow_mockups/DEO_ModifyCluster.jpg)

**Comment by subhaklp** [comment]
For the primary school hierarchy, need to be able to create block/cluster. Modify/delete is done. Preschool hierarchy, @aksanoble needs to comment.
