### ISSUE TITLE
DEO - Institutions CRUD

### ISSUE THREAD

**Issue by subhaklp** [klpdotorg/tada-frontend#34]

**Comment by aksanoble** [comment]
A DEO should be able to 

For Primary Schools
- [ ] Add a school to a boundary
- [ ] View all schools for each boundary
- [ ] Edit a school 
- [ ] Delete a school

For Primary Schools
- [ ] Add a school to a boundary
- [ ] View all schools for each boundary
- [ ] Edit a school 
- [ ] Delete a school
