### ISSUE TITLE
UX while modifying/deleting boundaries

### ISSUE THREAD

**Issue by subhaklp** [klpdotorg/tada-frontend#65]
The 'Save' and 'Delete' buttons are on the respective boundary screens. 
- When a user clicks "Save", should he/she be taken back to the dashboard home? Or allowed to continue where they were? 
- "Delete" should definitely force a reset to dashboard, right? '
- Should we have confirmation dialogs before they effect the changes?

Currently, we're battling some technical issues with keeping the nav tree in sync with these changes. So clarifying these will also clarify which issues we need to handle.

**Comment by meghaklp** [comment]
- Save should leave the user on the modify screen with a message saying changes were successfully saved, or indicate errors if any.
- Delete should reset dashboard
- We should have a confirmation before delete.
