### ISSUE TITLE
User registration

### ISSUE THREAD

**Issue by meghaklp** [klpdotorg/tada-frontend#87]
1. User registration accepted my registration without e-mail. If forgot password is going to work with e-mail only, e-mail should be mandatory. 
2. Mandatory field indications are needed. Or we say on top that all the below fields are mandatory and do a validation check if required fields are entered. 
3. Are we checking if the User already exists in the Database?
4. Upon registration, there's no indication if it were successful / not and we should probably lead to the login page instead of staying on the same page if it's been a success.

**Comment by subhaklp** [comment]
We decided we'd just get rid of this because it opens it up to too many people and we don't have the permissions bit worked out yet. Probably re-visit this at some later point if needed. I've fixed it in code so we don't show the registration button. Closing this.
