### ISSUE TITLE
Links

### ISSUE THREAD

**Issue by meghaklp** [klpdotorg/tada-frontend#89]
1) Clicking on KLP logo should always lead to some sort of home. On the login page - to the login screen,
After login to the Welcome splash

2) Support - should be a mailto link.

**Comment by vibhutipratapsingh** [comment]
Clicking on KLP lead to home page done.

**Comment by subhaklp** [comment]
Pending this for review.

**Comment by meghaklp** [comment]
Support is on the login page, it should have a mailto link attached.
