### ISSUE TITLE
Creating/ Modifying - Block Cluster

### ISSUE THREAD

**Issue by meghaklp** [klpdotorg/tada-frontend#92]
On successfully creating. The entity should get added to the tree we should navigate to that point on the tree and the Modify splash for the newly created Block/Cluster/District should show up.

**Comment by meghaklp** [comment]
On Modify also, we should not go back all the way to the Welcome splash. We should stay on the last visited node of the tree. Look at the interaction on the current day ems.

And on successful modification - we need some sort of success message and we continue to stay on the modify page

**Comment by meghaklp** [comment]
Not fixed, moving to beta 1

**Comment by meghaklp** [comment]
There's something wrong with the tree/ URLs still. For this particular District - I created a block, a cluster and then deleted them both. When I try to then add a new block to the same District, it just doesn't work.

![image](https://cloud.githubusercontent.com/assets/465382/24444543/4e13d6dc-1484-11e7-93d4-c6fe13fe9b29.png)

![image](https://cloud.githubusercontent.com/assets/465382/24444601/9204dd82-1484-11e7-89cd-88322c6595bf.png)

**Comment by subhaklp** [comment]
This is fixed now.

**Comment by meghaklp** [comment]
When  I try to create a New Block, under NEW DISTRICT 1 on the Nav Tree, it's getting created under NEW_DISTRICT_TEST - Something is badly messed up here.

![image](https://cloud.githubusercontent.com/assets/465382/25469018/386e3ae2-2b37-11e7-8d6c-0286ea158bf0.png)

**Comment by meghaklp** [comment]
Maybe something to do with which tree elements are expanded. Now when I close all tree elements and only open up New District 1, it created the block properly.

**Comment by subhaklp** [comment]
Hmm..I was able to recreate this on tada-staging once. After that, even with multiple nodes open, I don't see it anymore. Still trying to test. @vibhutipratapsingh @aksanoble can you guys try this?

**Comment by meghaklp** [comment]
I don't see this on staging anymore @subhaklp - You can close if you are all confident about it.

**Comment by subhaklp** [comment]
Closing after discussion with Megha. We should keep an eye open in case this pops up again.
