### ISSUE TITLE
Deleting boundaries

### ISSUE THREAD

**Issue by meghaklp** [klpdotorg/tada-frontend#93]
1) You can't delete a Block which has clusters or a District which has blocks

2) We need a confirmation dialog for Delete - "Are you sure you want to delete this Cluster?" or "Are you sure you want to delete this Block?"  - Add the question mark, please.

**Comment by meghaklp** [comment]
moving to beta 1

**Comment by subhaklp** [comment]
This is done. I've added an info banner message at the top of the screen to explain why the "delete" button is greyed out. I did this in lieu of showing tooltips/popovers over disabled buttons. If this doesn't work, open a separate bug please with desired UX.

**Comment by meghaklp** [comment]
When we delete a school, cluster, block it goes all the way back to the home screen. It should go to the immediate parent's modify screen.

Likely that after deleting the school / cluster/block, the user wants to create a different one in the same hierarchy. This is also how EMS used to behave.

**Comment by subhaklp** [comment]
Fixed this.
