### ISSUE TITLE
Create School - Issues

### ISSUE THREAD

**Issue by meghaklp** [klpdotorg/tada-frontend#95]
https://github.com/klpdotorg/tada_ui/raw/master/workflow_mockups/DEO_AddSchool.jpg

**Comment by meghaklp** [comment]
@aksanoble Can we not have all fields on the pop pup during school creation?

**Comment by vibhutipratapsingh** [comment]
I have added the fields in CreateSchool.

**Comment by meghaklp** [comment]
When I created the school - I got Anganwadi as a category (that should not happen) and though I selected it, the school was created as lower primary. 

For Schools the categories - should be lower,upper, model
For Preschools the categories - anganwadi, balwadi, independent balwadi

![image](https://cloud.githubusercontent.com/assets/465382/25469181/633d6d32-2b38-11e7-9453-85325ae1306d.png)

This is what got created:

![image](https://cloud.githubusercontent.com/assets/465382/25469218/9b51d8de-2b38-11e7-80cc-0e18dd935bfa.png)

**Comment by vibhutipratapsingh** [comment]
For Schools the categories - should be lower,upper, model
For Preschools the categories - anganwadi, balwadi, independent balwadi
done

**Comment by subhaklp** [comment]
@vibhutipratapsingh if you've fixed this, please add the "review" label and a comment here.
